name: dotnet_deploy01.yml

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal

#    - name: Publish # 배포 단계 추가
#      run: dotnet publish --no-build -c Release -o ./publish

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

    - name: archive drcloud 
      run: tar cvfz ./myapp_prod.tar.gz ${{env.DOTNET_ROOT}}/myapp


    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY  }}
        aws-secret-access-key: ${{ secrets.CICD_AWS_ACCESS_SECRET_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2   ./myapp_prod.tar.gz   s3://cicd-deploycodedir
      
    #- name: deploy with AWS codeDeploy
    #  run: aws deploy create-deployment
    #    --application-name github-wordpress_prod
    #    --deployment-config-name CodeDeployDefault.OneAtATime
    #    --deployment-group-name github-wordpress_prod
    #    --s3-location bucket=github-wordpress-deploy-bucket,bundleType=tgz,key=wordpress_prod.tar.gz


